// Auth Dispatch States
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';
export const TOKEN_LOCALSTORAGE_KEY = 'TOKEN'

// Profile Dispatch States
export const LOAD_USER_PROFILE_SUCCESS = 'LOAD_USER_PROFILE_SUCCESS';
export const LOAD_USER_PROFILE_FAIL = 'LOAD_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';


//Product Dispatch State
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PRODUCTS_FAIL = "LOAD_PRODUCTS_FAIL";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL ="DELETE_PRODUCT_FAIL"

// Varient Dispatch State
export const CREATE_VARIENT_SUCCESS = "CREATE_VARIENT_SUCCESS";
export const CREATE_VARIENT_FAIL = "CREATE_VARIENT_FAIL";
export const LOAD_VARIENTS_SUCCESS = "LOAD_VARIENTS_SUCCESS";
export const LOAD_VARIENTS_FAIL = "LOAD_VARIENTS_FAIL";
export const UPDATE_VARIENT_SUCCESS = "UPDATE_VARIENT_SUCCESS";
export const UPDATE_VARIENT_FAIL = "UPDATE_VARIENT_FAIL";
export const DELETE_VARIENT_SUCCESS = "DELETE_VARIENT_SUCCESS";
export const DELETE_VARIENT_FAIL ="DELETE_VARIENT_FAIL"


// POS System Dispatch State
export const GET_SKU_SUCCESS = "GET_SKU_SUCCESS";
export const GET_SKU_FAIL = "GET_SKU_FAIL";
// export const LOAD_VARIENTS_SUCCESS = "LOAD_VARIENTS_SUCCESS";
// export const LOAD_VARIENTS_FAIL = "LOAD_VARIENTS_FAIL";
// export const UPDATE_VARIENT_SUCCESS = "UPDATE_VARIENT_SUCCESS";
// export const UPDATE_VARIENT_FAIL = "UPDATE_VARIENT_FAIL";
// export const DELETE_VARIENT_SUCCESS = "DELETE_VARIENT_SUCCESS";
// export const DELETE_VARIENT_FAIL ="DELETE_VARIENT_FAIL"
//
export const HOST_URL = process.env.REACT_APP_HOST_URL || "http://localhost:8000"
export const CLIENT_ID = process.env.REACT_APP_CLIENT_ID || "clien_id"
export const CLIENT_SECRETE = process.env.REACT_APP_CLIENT_SECRET || "client_secrete"



// Location
export const LOAD_LOCATION_INFO_SUCCESS = "LOAD_LOCATION_INFO_SUCCESS";
export const LOAD_LOCATION_INFO_FAIL= "LOAD_LOCATION_INFO_FAIL";
export const UPDATE_LOCATION_INFO_SUCCESS = "UPDATE_LOCATION_INFO_SUCCESS";
export const UPDATE_LOCATION_INFO_FAIL = "UPDATE_LOCATION_INFO_FAIL";



